#!/usr/bin/env bash
# something

no_subdomain () {
	def_sub=( "www" "lb-01" "web-01" "web-02" )

	for i in "${def_sub[@]}"
	do
		cc="dig $i.$1 | grep ^$i.$1."
		content=$(eval $cc)
		record=$(echo $content | awk -F' ' '{ print $4 }')
		ip=$(echo $content | awk -F' ' '{print $5}')
		echo "The subdomain $i is a $record record and points to $ip"
	done
}

given_subdomain () {
	cc="dig $2.$1 | grep ^$2.$1."
	content=$(eval $cc)
	record=$(echo $content | awk -F' ' '{ print $4 }')
	ip=$(echo $content | awk -F' ' '{print $5}')
	echo "The subdomain $2 is a $record record and points to $ip"
}
if [ $# -eq 1 ]; then
	no_subdomain $1
else
	given_subdomain $1 $2
fi
