#!/usr/bin/env bash
# Transfer files from out client to our server (using scp)

if [ $# -lt 3 ]
then
	echo 'Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY '
else
	scp -i $4 $1 $3@$2:~/
fi
