#!/usr/bin/env bash
# Configure HAProxy on a new server (load balancer)
# This is for a Ubuntu Focal 20.04 LTS. HAProxy version 2.7-stable

sudo apt-get -y update
sudo apt-get -y install --no-install-recommends software-properties-common
sudo add-apt-repository -y ppa:vbernat/haproxy-2.7
sudo apt-get -y install haproxy=2.7.\*

conf_file=\
"frontend myfrontend
        mode http
        bind *:80
        default_backend myservers

backend myservers
        mode http
	balance roundrobin
	server 162122-web-01 100.25.31.18:80 check
        server 162122-web-02 34.232.78.18:80 check
echo "$conf_file" | sudo tee -a /etc/haproxy/haproxy.cfg 
echo "ENABLED=1" | sudo tee -a /etc/default/haproxy
sudo service haproxy start
