#!/usr/bin/env bash
#later people

function end(){
	rm /var/run/myscript.pid
	exit
}

echo "$$" > /var/run/myscript.pid

trap "echo 'I hate the kill command' && end" SIGTERM
trap "echo 'Y U no love me?!'" SIGINT
trap end SIGQUIT

while true;do
	echo "To infinity and beyond"
	sleep 2
done
