#!/usr/bin/env bash
#display the content of the `/etc/passwd` file with only a few portions

# shellcheck disable=SC2034
# Unused variables left for readability
FILENAME="/etc/passwd"

while IFS=: read -r f1 f2 f3 f4 f5 f6 f7
do
	echo "$f1:$f3:$f6"
done < $FILENAME
