#!/usr/bin/env bash
#display `bad luck` on the fourth iteratin and `good luck` on the eighth
#The rest display `Best School`

x=0
while [ $x -lt 10 ]
do
	if [ $x -eq 3 ]
	then
		echo "bad luck"
	elif [ $x -eq 7 ]
	then
		echo "good luck"
	else
		echo "Best School"
	fi
	((x++))
done
