#!/usr/bin/env bash
#Print 1 - 20 with some statements at specific places

x=1

while [ $x -le 20 ]
do
	echo $x
	case $x in

		4)
			echo "bad luck from China"
			;;
		9)
			echo "bad luck from Japan"
			;;
		17)
			echo "bad luck from Italy"
	esac
	((x++))
done
