#!/usr/bin/env bash
#Write a Bash script that displays the time for 12 hours and 59 minutes:

x=1
h=0

while [ $h -le 12 ]
do
	echo "Hour: $h"
	while [ $x -le 59 ]
	do
		echo $x
		((x++))
	done
	((h++))
	x=1
done
